flaskr/libreria/models.py
from flaskr import db
from flaskr.auth.models import Usuario
from flask import url_for

class Categoria(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(30), nullable=False)

class Libro(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80), nullable=False)
    autor = db.Column(db.String(30), nullable=False)
    image = db.Column(db.LargeBinary, nullable=False)
    PDF = db.Column(db.LargeBinary, nullable=False)
    EPUB = db.Column(db.LargeBinary, nullable=False)
    categoriaId = db.Column(db.ForeignKey('categoria.id'), nullable=False)
    usuarioId = db.Column(db.ForeignKey('usuario.id'), nullable=False)
    created = db.Column(
        db.DateTime, nullable=False, server_default=db.func.current_timestamp()
        ) 
    descargas = db.Column(db.Integer, default=0)

     # User object backed by author_id
    # lazy="joined" means the user is returned with the post in one query
    # autor = db.relationship(Usuario, lazy="joined", backref="posts")

    @property
    def delete_url(self):
        return url_for("libreria.delete", id=self.id)

    @property
    def download_url(self):
        return url_for("libreria.download", id=self.id)

    @property
    def download_pdf(self):
        return url_for("libreria.downloadpdf", id=self.id)

    @property
    def download_epub(self):
        return url_for("libreria.downloadepub", id=self.id)

flaskr/libreria/__init__.py
from .views import bp

flaskr/libreria/views.py
from flask import url_for, send_file, Blueprint, flash, redirect, render_template, request, g
from werkzeug.exceptions import abort

from flaskr import db
from flaskr.auth.views import login_required
from flaskr.libreria.models import Libro, Categoria
from flaskr.auth.models import Usuario

from base64 import b64encode
from io import BytesIO

bp = Blueprint("libreria", __name__)

#Index where appears a list of books
@bp.route("/")
def index():
    """Show all the books, most recent first."""
    libros = Libro.query.order_by(Libro.created.desc()).all()
    for libro in libros:
        #Encode the image to send by the network
        libro.image = b64encode(libro.image).decode('ascii')
    return render_template("libreria/index.html", libros=libros)

#Search a book
@bp.route('/explorar', methods=('GET','POST'))
def explorar():
   if request.method == 'POST':
        busqueda = request.form['busqueda'].lower()
        libroReturn = []
        libros = Libro.query.order_by(Libro.created.desc()).all()
        for libro in libros:
            #Encode the image to send by the network
            if busqueda in libro.name.lower() or busqueda in libro.autor.lower():
                libro.image = b64encode(libro.image).decode('ascii')
                libroReturn.append(libro)
        return render_template('explorar.html',libros=libroReturn) 
   return render_template('explorar.html')


def get_libro(id, check_author=True):
    """Get a post and its author by id.

    Checks that the id exists and optionally that the current user is
    the author.

    :param id: id of post to get
    :param check_author: require the current user to be the author
    :return: the post with author information
    :raise 404: if a post with the given id doesn't exist
    :raise 403: if the current user isn't the author
    """
    libro = Libro.query.get_or_404(id, f"Post id {id} doesn't exist.")

    if check_author and libro.usuarioId != g.user.id:
        abort(403)

    return libro

@bp.route("/create", methods=("GET", "POST"))
@login_required
def create():
    """Create a new libro/book for the current user."""
    if request.method == "POST":
        titulo = request.form["titulo"] #title
        autorform = request.form["autor"] #Author
        pdf = request.files['pdf'] 
        imagen = request.files['portada'] #Coverpage
        epub = request.files["epub"] 
        categoria = request.form["categoria"] 
        #Search categoria id
        categoriaid = Categoria.query.filter_by(name=categoria).first().id
        error = None
        if not titulo:
            error = "Titulo is required."
        if error is not None:
            flash(error)
        else:
            db.session.add(Libro(name=titulo, autor=autorform, image=imagen.read(), EPUB=epub.read(), PDF=pdf.read(), categoriaId=categoriaid, usuarioId=g.user.id))
            db.session.commit()
            flash("Libro creado", "success")
            libros = Libro.query.order_by(Libro.created.desc()).all()
            return redirect(url_for("libreria.index", libros=libros ))

    return render_template("libreria/create.html", categorias=Categoria.query.all())


@bp.route("/<int:id>/download")
def download(id):
    """Download a book page"""
    libro = get_libro(id, check_author=False)
    libro.image = b64encode(libro.image).decode('ascii')
    return render_template("libreria/download.html", libro=libro)

#Download pdf button
@bp.route("/<int:id>/download/pdf")
def downloadpdf(id):
    libro = get_libro(id, check_author=False)
    libro.descargas = libro.descargas + 1
    db.session.commit()
    return send_file(BytesIO(libro.PDF), attachment_filename=libro.name + ".pdf", as_attachment=True)

#Download EPUB button
@bp.route("/<int:id>/download/epub")
def downloadepub(id):
    libro = get_libro(id, check_author=False) 
    return send_file(BytesIO(libro.EPUB), attachment_filename=libro.name + ".epub", as_attachment=True)

#See my (User's) books
@bp.route("/mybooks")
@login_required
def mybooks():
    libros = Libro.query.filter_by(usuarioId=g.user.id).order_by(Libro.created.desc()).all()
    return render_template("libreria/mybooks.html", libros=libros)

#Delete one of our books
@bp.route("/<int:id>/delete")
@login_required
def delete(id):
    """Delete a book.

    Ensures that the book exists and that the logged in user is the
    author of the post.
    """
    libro = get_libro(id) #This also checks that is the author
    db.session.delete(libro)
    db.session.commit()
    return redirect(url_for("libreria.index"))

flaskr/templates/libreria/create.html
{% extends 'base.html' %}

{% block navbar %}
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top mb-5 shadow">
  <div class="container">
    <a class="navbar-brand" href="{{ url_for('index') }}">Libreria FDR</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('index') }}"><i class="fa fa-home" aria-hidden="true"></i>
 {{_('Home')}}
                        <span class="sr-only">(current)</span>
                        </a>
                </li>
                <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('libreria.explorar') }}"><i class="fa fa-search" aria-hidden="true"></i> {{ _('Search') }}</a>
                </li>
                <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('telegram') }}"><i class="fa fa-envelope-o" aria-hidden="true"></i> {{_('Contact')}} </a>
                </li>
                {% if g.user %}
                        <li class="nav-item active">
                                <a class="nav-link" href="{{ url_for('libreria.create') }}"><i class="fa fa-plus" aria-hidden="true"></i> {{ _('UploadBook')}}</a>
                        </li>
                        <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('libreria.mybooks') }}"><i class="fa fa-book" aria-hidden="true"></i> {{_('MyBooks')}}</a>
                        </li>
                {% endif %}
        <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-globe" aria-hidden="true"></i>
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="{{ url_for('set_language', language='en') }}" >en</a>
                        <a class="dropdown-item" href="{{ url_for('set_language', language='es') }}" >es</a>
                        <a class="dropdown-item" href="{{ url_for('set_language', language='eu_ES') }}" >eus</a>
                </div>
        </div>
        </ul>
        <ul class="navbar-nav ml-auto">
                {% if g.user %}
                        <li><span class="username">{{ g.user['username'] }}</span>
                                <li><a href="{{ url_for('auth.logout') }}">{{_('LogOut')}}</a>
                {% else %}
                        <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('auth.login') }}">{{_('LogIn')}}</a>
                        </li>
                        <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('auth.register') }}">{{_('Register')}}</a>
                        </li>
                {% endif %}
        </ul>
    </div>
  </div>
</nav>




{% endblock %}


{% block header %}
<h1>{{_('UploadBook')}}</h1>
{% endblock %}

{% block content %}
        <form method="post" enctype=multipart/form-data>
		<label for="basic-url">{{_('Book')}}</label>
                <div class="form-group">
			<label for="Nombre">{{_('Title')}}</label>
                        <input type="text" class="form-control" placeholder="Titulo" aria-describedby="basic-addon1" name="titulo" id="titulo" required>
                </div>
                <div class="form-group">
			<label for="Nombre">{{_('Author')}}</label>
                        <input type="text" class="form-control" placeholder="Autor" aria-describedby="basic-addon1" name="autor" id="autor" required>
                </div>
              
                <div class="form-group">
			<label for="Nombre">{{_('ImageCoverpage')}}</label>
                        <input type="file" class="form-control" placeholder="portada" aria-describedby="basic-addon1" name="portada" id="portada" required>
                </div>
		
                <div class="form-group">
			<label for="Nombre">{{_('UploadPDF')}}</label>
                        <input type="file" class="form-control" placeholder="PDF" aria-describedby="basic-addon1" name="pdf" id="pdf" required>
                </div>
	
                <div class="form-group">
			<label for="Nombre">{{_('UploadEPUB')}}</label>
                        <input type="file" class="form-control" placeholder="EPUB" aria-describedby="basic-addon1" name="epub" id="epub" required>
                </div>
	
                <div class="form-group">
			<label for="Nombre">{{_('Category')}}</label>
                	<select class="form-control" name="categoria" id="categoria">
				{% for categoria in categorias %}
      					<option> {{ categoria.name }} </option>
		                {% endfor %}
    			</select>
		</div>

		<input type="submit" class="btn btn-success" value="{{_('Send')}}">
        </form>
{% endblock %}

flaskr/templates/libreria/download.html
{% extends 'base.html' %}




{% block header %}
<h1>{% block title %}{{libro.name}}{% endblock %}</h1>
{% endblock %}

{% block content %}
	<div class="jumbotro">
		<p class="lead">
		<div class="center">
				<img class="img-fluid" src="data:image/png;base64,{{ libro.image }}" alt="...">
		</div>
		</p>
  		<hr class="my-4">
		<p> {{_('Author')}} {{ libro.autor }} </p>
		<p> {{_('Uploaded')}} {{ libro.created }} </p>
		<p> {{_('Downloads')}} {{ libro.descargas }} </p>
		<div class="center" id="downloadButton">
			<a class="btn btn-primary btn-lg" href="{{libro.download_pdf}}" role="button">PDF</a>
			<div class="divider"></div>
			<a class="btn btn-secondary btn-lg" href="{{libro.download_epub}}" role="button">EPUB</a>
		</div>	
	</div>
{% endblock %}

flaskr/templates/libreria/index.html
{% extends 'base.html' %}

{% block header %}
	<h1>{% block title %}LIBRERIA FDR{% endblock %}</h1>
{% endblock %}

{% block content %}

	{% if libros is defined %}
		<div class="row">
		{% for libro in libros %}
  				<div class="col-sm-6 col-md-4">
    					<div class="thumbnail">
						<img class= "img-thumbnail" src="data:image/png;base64,{{ libro.image }}" alt="...">
      						<div class="caption">
							<h3> {{libro.name}} </h3>
							<p>{{_('Author')}} {{libro.autor}}</p>
							<p>{{_('Uploaded')}} {{libro.created}}</p>
							<p><a href=" {{ libro.download_url }}" class="btn btn-primary" role="button">{{_('Download')}}</a></p>
      						</div>
    					</div>
  				</div>
		{% endfor %}
		</div>
	{% else %}
		<span> LIBROS	LIBROS	LIBROS	.. </span>
	{% endif %}
{% endblock %}

flaskr/templates/libreria/mybooks.html
{% extends 'base.html' %}

{% block navbar %}
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top mb-5 shadow">
  <div class="container">
    <a class="navbar-brand" href="#{{ url_for('index') }}">Libreria FDR</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('index') }}"><i class="fa fa-home" aria-hidden="true"></i>
 {{_('Home')}}
                        <span class="sr-only">(current)</span>
                        </a>
                </li>
                <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('libreria.explorar') }}"><i class="fa fa-search" aria-hidden="true"></i> {{ _('Search') }}</a>
                </li>
                <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('telegram') }}"><i class="fa fa-envelope-o" aria-hidden="true"></i> {{_('Contact')}} </a>
                </li>
                {% if g.user %}
                        <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('libreria.create') }}"><i class="fa fa-plus" aria-hidden="true"></i> {{ _('UploadBook')}}</a>
                        </li>
                        <li class="nav-item active">
                                <a class="nav-link" href="{{ url_for('libreria.mybooks') }}"><i class="fa fa-book" aria-hidden="true"></i> {{_('MyBooks')}}</a>
                        </li>
                {% endif %}
        <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-globe" aria-hidden="true"></i>
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="{{ url_for('set_language', language='en') }}" >en</a>
                        <a class="dropdown-item" href="{{ url_for('set_language', language='es') }}" >es</a>
                        <a class="dropdown-item" href="{{ url_for('set_language', language='eu_ES') }}" >eus</a>
                </div>
        </div>
        </ul>
        <ul class="navbar-nav ml-auto">
                {% if g.user %}
                        <li><span class="username">{{ g.user['username'] }}</span>
                                <li><a href="{{ url_for('auth.logout') }}">{{_('LogOut')}}</a>
                {% else %}
                        <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('auth.login') }}">{{_('LogIn')}}</a>
                        </li>
                        <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('auth.register') }}">{{_('Register')}}</a>
                        </li>
                {% endif %}
        </ul>
    </div>
  </div>
</nav>




{% endblock %}


{% block header %}
<h1>{{_('MyBooks')}}</h1>
{% endblock %}

{% block content %}
	{% for libro in libros %}
		<h3> {{libro.name}} </h3>
		<p>{{_('Author')}} {{libro.autor}}</p>
		<p>{{_('Uploaded')}} {{libro.created}}</p>
		<p><a href=" {{ libro.delete_url }}" class="btn btn-primary" role="button">Delete</a></p>
		<hr>
	{% endfor %}
{% endblock %}